apiVersion: apps/v1
kind: Deployment
metadata:
  name: homecare-app
spec:
  template:
    spec:
      containers:
      - name: homecare-app
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: NODE_ENV
          value: "production"
