apiVersion: apps/v1
kind: Deployment
metadata:
  name: homecare-app
spec:
  template:
    spec:
      containers:
      - name: homecare-app
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: NODE_ENV
          value: "development"
